src/apps/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.contrib.sitemaps.views import sitemap
from django.urls import path
from graphene_django.views import GraphQLView

import apps.views as apps_views
import article.views as article_views
import contact.views as contact_views
import utils.views as utils_views
from apps.admin import AutoGenerateAdminSite

from .sites import ArticleRssFeed, sitemaps

urlpatterns = (
    [
        path("admin/native/", AutoGenerateAdminSite().urls),
        path("profile/", apps_views.ProfileView.as_view(), name="profile"),
        path("sitemap.xml/", sitemap, {"sitemaps": sitemaps}, name="sitemap"),
        path("rss/", ArticleRssFeed(), name="rss"),
        path("", article_views.ArticleListView.as_view(), name="article_list"),
        path("contact/", contact_views.ContactView.as_view(), name="contact"),
        path("utils/", utils_views.UtilListView.as_view(), name="utils_list"),
        path("utils/qrcode/", utils_views.QRCodeGeneratorView.as_view(), name="utils_qrcode"),
        path("utils/markdown/", utils_views.MarkdownEditorView.as_view(), name="utils_markdown"),
        path("utils/rakuten/", login_required(utils_views.RakutenConverterView.as_view()), name="utils_rakuten"),
        path(
            "utils/mufj_debit/", login_required(utils_views.MUFJDebitConverterView.as_view()), name="utils_mufj_debit"
        ),
        path("utils/csv_to_md/", utils_views.CSVTOMDConvertorView.as_view(), name="utils_csv_to_md"),
        path("<str:uuid>/", article_views.ArticleDetailView.as_view(), name="article_detail"),
        path("api/v1/graphql/", GraphQLView.as_view(graphiql=True)),
    ]
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

src/utils/forms.py
from django import forms


class RakutenForm(forms.Form):
    pdf = forms.FileField(label="pdf")


class MUFJForm(forms.Form):
    pdf = forms.FileField(label="pdf")

src/utils/views.py
from typing import List

import tabula
from django.http.response import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views.generic import FormView, TemplateView
from pandas.core.frame import DataFrame

from utils.forms import RakutenForm


class UtilListView(TemplateView):
    template_name = "utils/index.html"


class QRCodeGeneratorView(TemplateView):
    template_name = "utils/qrcode.html"


class MarkdownEditorView(TemplateView):
    template_name = "utils/markdown.html"


class RakutenConverterView(FormView):
    template_name = "utils/rakuten.html"
    form_class = RakutenForm
    table_headers = ["利用日", "利用店名", "利用者", "支払方法", "利用金額", "手数料", "支払総額", "当月請求額", "翌月繰越残高"]

    def form_valid(self, form: RakutenForm):
        file = self.request.FILES["pdf"]
        tables: List[DataFrame] = tabula.read_pdf(file, lattice=True, pages="all")
        result_table = DataFrame()
        for table in tables:
            if not list(table.columns) == self.table_headers:
                continue
            result_table = result_table.append(table)
        if len(result_table):
            response = HttpResponse(content_type="text/csv")
            filename = "rakuten.csv"
            response["Content-Disposition"] = f"attachment; filename={filename}"
            result_table = result_table[["利用日", "利用店名", "利用金額"]].dropna()
            result_table["利用金額"] = result_table["利用金額"].dropna().astype(str).str.replace(",", "").astype(int)
            response.write(result_table.sort_values("利用日").to_csv(index=False))
        else:
            response = HttpResponseRedirect(reverse("utils_rakuten"))
        return response


class CSVTOMDConvertorView(TemplateView):
    template_name = "utils/csv_to_md.html"


class MUFJDebitConverterView(FormView):
    template_name = "utils/mufj_debit.html"
    form_class = RakutenForm

    def form_valid(self, form: RakutenForm):
        file = self.request.FILES["pdf"]
        tables: List[DataFrame] = tabula.read_pdf(file, lattice=False, pages="all")
        result_table = DataFrame()
        for table in tables:
            if not list(table.columns)[0] == "お取引日 お取引内容":
                continue
            table[["お取引日", "お取引内容"]] = table["お取引日 お取引内容"].str.split(n=1, expand=True)
            table = table.dropna(subset=["お取引日", "お取引内容", "ご利用額"]).rename(
                columns={"お取引日": "利用日", "お取引内容": "利用店名", "ご利用額": "利用金額"}
            )
            result_table = result_table.append(table[["利用日", "利用店名", "利用金額"]])
        if len(result_table):
            response = HttpResponse(content_type="text/csv")
            filename = "mufj.csv"
            response["Content-Disposition"] = f"attachment; filename={filename}"
            result_table["利用金額"] = result_table["利用金額"].astype(str).str.replace(",", "").astype(int)
            response.write(result_table.sort_values("利用日").to_csv(index=False))
        else:
            response = HttpResponseRedirect(reverse("utils_mufj_debit"))
        return response

src/templates/utils/csv_to_md.html
{% extends "base.html" %}

{% block header %}
<title>kemuのブログ | CSVTOMD Convertor</title>
<meta property="og:title" content="kemuのブログ | CSVTOMD Convertor" >
{% endblock %}
{% block content %}
<h2>CSVTOMD Convertor</h2>
<div class="row border-top border-bottom" style="height: 80%; overflow-y: scroll;">
    <div class="col-6">
        <textarea 
            oninput="syncHtml()" 
            style="height: 100%; tab-size: 4;" 
            class="form-control" 
            id="csv"></textarea>
    </div>
    <div class="col-6">
        <div class="d-flex flex-row-reverse" >
            <button class="btn btn-sm btn-outline-primary" style="position: absolute;" onclick="copyText()"><i class="bi bi-clipboard"></i></button>
        </div>
        <div id="output" style="white-space: break-spaces;"></div>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/csv-to-markdown-table@1.1.0/lib/CsvToMarkdown.min.js"></script>
<script type="text/javascript">
function syncHtml() {
    const csv = document.getElementById("csv").value
    document.getElementById("output").innerText = csvToMarkdown(csv, ",", true)
}
function copyText() {
    window.navigator.clipboard.writeText(document.getElementById("output").innerText)
}
</script>
{% endblock %}

src/templates/utils/index.html
{% extends 'base.html' %}

{% block header %}
<title>kemuのブログ | 便利ツール集</title>
<meta property="og:title" content="kemuのブログ | 便利ツール集" >
{% endblock %}
{% block content %}
<h2>便利ツール集</h2>
<p>鍵マークの記載してある機能は有料機能になるため<a href="{% url 'contact' %}">Contact</a>より問い合わせを行ってください。</p>
<button class="card w-100 mt-2 no-deco" onclick="window.location.href='{% url "utils_qrcode" %}'">
  <div class="card-body w-100 text-secondary">
    <div class="card-title d-flex justify-content-between">
      QRコードジェネレータ
    </div>
    <p class="card-text text-start">任意の文字列をQRコードに変換します。</p>
  </div>
</button>
<button class="card w-100 mt-2 no-deco" onclick="window.location.href='{% url "utils_markdown" %}'">
  <div class="card-body w-100 text-secondary">
    <div class="card-title d-flex justify-content-between">
      Markdown Editor
    </div>
    <p class="card-text text-start">markdown記法で書かれた文字列をHTMLで表示します。</p>
  </div>
</button>
<button class="card w-100 mt-2 no-deco" onclick="window.location.href='{% url "utils_csv_to_md" %}'">
  <div class="card-body w-100 text-secondary">
    <div class="card-title d-flex justify-content-between">
      CSV to MD table
    </div>
    <p class="card-text text-start">コンマ区切りで入力されたcsvをMarkdownテーブル形式に変換します。</p>
  </div>
</button>
<button class="card w-100 mt-2 no-deco" onclick="window.location.href='{% url "utils_rakuten" %}'" {% if not user.is_authenticated %} disabled {% endif %}>
  <div class="card-body w-100 text-secondary">
    <div class="card-title d-flex justify-content-between">
      楽天カード履歴変換<i class="bi bi-lock"></i>
    </div>
    <p class="card-text text-start">楽天カードの利用履歴PDFからデータを抽出し、csvに変換します。</p>
  </div>
</button>
<button class="card w-100 mt-2 no-deco" onclick="window.location.href='{% url "utils_mufj_debit" %}'" {% if not user.is_authenticated %} disabled {% endif %}>
  <div class="card-body w-100 text-secondary">
    <div class="card-title d-flex justify-content-between">
      MUFJ Debit履歴変換<i class="bi bi-lock"></i>
    </div>
    <p class="card-text text-start">MUFJ Debitカードの利用履歴PDFからデータを抽出し、csvに変換します。</p>
  </div>
</button>
{% endblock %}

src/templates/utils/markdown.html
{% extends 'base.html' %}

{% block header %}
<title>kemuのブログ | Markdown Editor</title>
<meta property="og:title" content="kemuのブログ | Markdown Editor" >
{% endblock %}
{% block content %}
<h2>Markdown Editor</h2>
<div class="row border-top border-bottom" style="height: 80%; overflow-y: scroll;">
    <div class="col-6">
        <div class="d-flex flex-row-reverse" >
            <button class="btn btn-sm btn-outline-primary" style="position: absolute;" onclick="copyText()"><i class="bi bi-clipboard"></i></button>
        </div>
        <textarea 
            oninput="syncHtml()" 
            onkeydown="markdownComplement(event, this)" 
            style="height: 100%; tab-size: 4;" 
            class="form-control" 
            id="markdown"></textarea>
    </div>
    <div class="col-6" id="output"></div>
</div>
<script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
<script type="text/javascript">
document.getElementById("markdown").value = localStorage.getItem("markdown")
syncHtml()
function syncHtml() {
    const markdown = document.getElementById("markdown").value
    document.getElementById("output").innerHTML = marked.parse(markdown)
    localStorage.setItem("markdown", markdown)
}
function markdownComplement(event, object) {
    // キーコードと入力された文字列
    var keyCode = event.keyCode;
    var keyVal = event.key;
    // カーソル位置
    var cursorPosition = object.selectionStart;
    var leftString = object.value.substr(0, cursorPosition);
    var rightString = object.value.substr(cursorPosition, object.value.length);

    // タブキーの場合
    if(keyCode === 9) {
        event.preventDefault();
        object.value = leftString + "\t" + rightString;
        object.selectionEnd = cursorPosition + 1;
    }
}
function copyText() {
    window.navigator.clipboard.writeText(document.getElementById("markdown").value)
}
</script>
{% endblock %}

src/templates/utils/mufj_debit.html
{% extends "base.html" %}

{% block header %}
<title>kemuのブログ | MUFJ Debit履歴変換</title>
<meta property="og:title" content="kemuのブログ | MUFJ Debit履歴変換" >
{% endblock %}
{% block content %}
<h2>MUFJ Debit履歴変換</h2>
<form method="POST" enctype="multipart/form-data">{% csrf_token %}
    <label for="formFile" class="form-label">PDF</label>
    <input class="form-control" type="file" name="pdf" required id="id_pdf">
    <div class="mt-3">
        <button type="submit" class="btn btn-success">変換</button>
    </div>
</form>
{% endblock %}

src/templates/utils/qrcode.html
{% extends "base.html" %}

{% block header %}
<title>kemuのブログ | QRコードジェネレータ</title>
<meta property="og:title" content="kemuのブログ | QRコードジェネレータ" >
{% endblock %}
{% block content %}
<h3>QRコードジェネレータ</h3>
<p>文字列をQRコードに変換します。変換した履歴はローカルストレージにのみ保存され、サーバーには保存されません</p>

<label for="qrcodeString" class="form-label">変換するテキスト</label>
<input id="qrcodeString" class="form-control" onblur="generateQRcode()" />
<div class="my-4 d-flex justify-content-center">
    <div id="qrcode"></div>
</div>
履歴
<div class="list-group" id="history"></div>
<script src="https://cdn.jsdelivr.net/npm/davidshimjs-qrcodejs@0.0.2/qrcode.min.js"></script>
<script type="text/javascript">
const defaultQrcodeString = localStorage.getItem("qrcodeString")
const convertHistory = JSON.parse(localStorage.getItem("convertHistory") || "[]")
qrcode = new QRCode(document.getElementById("qrcode"), defaultQrcodeString)
document.getElementById("qrcodeString").value = defaultQrcodeString
displayHistory()

function generateQRcode() {
    const qrcodeString = document.getElementById("qrcodeString").value
    if (localStorage.getItem("qrcodeString") !== qrcodeString) {
        convertHistory.push(qrcodeString)
    }
    if (qrcodeString) {
        qrcode.makeCode(qrcodeString)
    }
    localStorage.setItem("qrcodeString", qrcodeString)
    displayHistory()
}

function displayHistory() {
    const historyDom = document.getElementById("history")
    historyDom.innerHTML = ""
    convertHistory.slice().reverse().forEach(qrcodeString => {
        var li = document.createElement("button");
        li.setAttribute("class", "list-group-item list-group-item-action")
        li.textContent = qrcodeString;
        li.onclick = () => {
            document.getElementById("qrcodeString").value = qrcodeString
            generateQRcode()
        }
        historyDom.appendChild(li);
    })
    localStorage.setItem("convertHistory", JSON.stringify(convertHistory.slice(-5)))
}
</script>
{% endblock %}

src/templates/utils/rakuten.html
{% extends "base.html" %}

{% block header %}
<title>kemuのブログ | 楽天カード履歴変換</title>
<meta property="og:title" content="kemuのブログ | QRコードジェネレータ" >
{% endblock %}
{% block content %}
<form method="POST" enctype="multipart/form-data">{% csrf_token %}
    <label for="formFile" class="form-label">PDF</label>
    <input class="form-control" type="file" name="pdf" required id="id_pdf">
    <div class="mt-3">
        <button type="submit" class="btn btn-success">変換</button>
    </div>
</form>
{% endblock %}